os:
- linux
services:
- docker
- redis
- cassandra
- memcached
sudo: required

language: go
go:
    - 1.8
    - 1.8.3
    - 1.9
env:
    - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
    - git config --global url."git@github.com:".insteadOf "https://github.com/"
    - go get -u github.com/Masterminds/glide
install:
    - docker-compose -f test/docker-compose.yml up -d nats kafka es1 es2 es5
    - glide cc
    - glide update -v --force
script:
    - go test -v -race -cpu 1,2,4,8 -cover -run=. -bench=. ./services/...
