os:
- linux
services:
- docker
- redis
- cassandra
- memcached
sudo: required

language: go
go:
    - 1.8.4
    - 1.9.2
env:
    - PATH=/home/travis/gopath/bin:$PATH
before_install:
    - make -f Makefile.ci deps_external
    - make -f Makefile.ci tools_external
install:
    - make -f Makefile deps
    - docker-compose -f test/docker-compose.yml up -d nats kafka es1 es2 es5
script:
    - make -f Makefile.ci tests
    - make -f Makefile.ci coverage
