
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "~1.13.0"

[[constraint]]
  name = "github.com/bsm/sarama-cluster"
  version = "~2.1.8"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "~1.1.0"

[[constraint]]
  revision = "2e7ada62e73eec9d70e5558e2a08d6925ba20226"
  name = "github.com/gocql/gocql"

[[constraint]]
  name = "github.com/google/uuid"
  version = "~0.2.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "~0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rainycape/memcache"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.1.4"

[[constraint]]
  name = "go.uber.org/zap"
  version = "~1.7.1"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v2"
  version = "~2.0.60"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v3"
  version = "~3.0.71"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v5"
  version = "~5.0.52"
