.PHONY: toc test bench test-bench

toc:
	docker run --rm -it -v ${PWD}:/usr/src jorgeandrada/doctoc --github

test:
	staticcheck ./...
	go vet ./...
	go test -v -race -cpu 1,2,4,8,24 -cover -run=. -bench=. ./...

bench:
	go test -v -cpu 1,2,4,8,24 -cover -run=xxx -bench=. ./...

test-bench:
	go test -v -cpu 1,2,4,8,24 -cover -run=. -bench=. ./...
